language: python
python:
    - "2.7"
script:
    - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
    - git fetch
    - git diff --name-only --diff-filter=AM HEAD origin/${TRAVIS_BRANCH} | grep ".xml" | tee /dev/stderr | xargs -d "\n" xmllint --noout
    - python create_compendiums.py --excludes
before_install:
      - sudo apt-get install -y libxml2-utils
